version: '3'
services:
  web:
    build: '.'
    command: 'npm start'
    env_file:
      - './.env'
    volumes:
      - '.:/app'
    ports:
      - '3000:3000'
  mongo:
      image: mongo:4.0
      restart: always
      volumes:
        - 'mongo-data:/data/db'
      ports:
      - '2717:27017'
      env_file:
        - './.env'
volumes:
  mongo-data: {}
